<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="16" xOffset="0" scrollWidth="726" startPos="1060" endPos="1060" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\Truck.java" backupFilePath="" originalFileLastModifTimestamp="1520395805" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7864439" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="72" xOffset="0" scrollWidth="1067" startPos="2843" endPos="2844" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\DijkstraUndirectedSP.java" backupFilePath="" originalFileLastModifTimestamp="1520391139" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1723937104" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1408" startPos="4196" endPos="4196" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\IndexMinPQ.java" backupFilePath="" originalFileLastModifTimestamp="1520391182" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1143275520" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="3" xOffset="0" scrollWidth="1100" startPos="628" endPos="628" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\Edge.java" backupFilePath="" originalFileLastModifTimestamp="1520383794" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1331" startPos="395" endPos="395" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\EdgeList.java" backupFilePath="" originalFileLastModifTimestamp="1520391212" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no">
                <Fold line="45" />
                <Fold line="82" />
            </File>
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1067" startPos="1247" endPos="1247" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\EdgeWeightedGraph.java" backupFilePath="" originalFileLastModifTimestamp="1520390954" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1279246063" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="121" startPos="0" endPos="0" selMode="0" lang="Normal Text" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\truck\sample_1.in" backupFilePath="" originalFileLastModifTimestamp="1470784248" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="42" xOffset="0" scrollWidth="814" startPos="1939" endPos="1939" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\GitHub\uvic\LinkedList.java" backupFilePath="" originalFileLastModifTimestamp="1520389954" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="6357108" mapWrapIndentMode="-1" mapIsWrap="no">
                <Fold line="52" />
            </File>
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
