<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="27" xOffset="0" scrollWidth="1221" startPos="1108" endPos="1108" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\Arbitrage.java" backupFilePath="" originalFileLastModifTimestamp="1520385604" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1279246063" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="4" xOffset="0" scrollWidth="1331" startPos="1243" endPos="1243" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\DirectedEdge.java" backupFilePath="" originalFileLastModifTimestamp="1520385691" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1331" startPos="1973" endPos="1975" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\DirectedEdgeList.java" backupFilePath="" originalFileLastModifTimestamp="1520387688" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no">
                <Fold line="81" />
                <Fold line="165" />
            </File>
            <File firstVisibleLine="21" xOffset="0" scrollWidth="1188" startPos="1312" endPos="1312" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\EdgeWeightedDigraph.java" backupFilePath="" originalFileLastModifTimestamp="1520388231" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1279246063" mapWrapIndentMode="-1" mapIsWrap="no">
                <Fold line="38" />
            </File>
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1001" startPos="995" endPos="997" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\EdgeWeightedDirectedCycle.java" backupFilePath="" originalFileLastModifTimestamp="1520377989" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="118" xOffset="0" scrollWidth="1078" startPos="5092" endPos="5094" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\BellmanFord.java" backupFilePath="" originalFileLastModifTimestamp="1520388073" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="63" xOffset="0" scrollWidth="1166" startPos="0" endPos="0" selMode="0" lang="Java" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\Queue.java" backupFilePath="" originalFileLastModifTimestamp="1520275923" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-16777216" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="132" startPos="0" endPos="0" selMode="0" lang="Normal Text" encoding="-1" filename="C:\Users\marca\Documents\TextBooks\spr18\CSC226\code226\a4\arbitrage\sample.in" backupFilePath="" originalFileLastModifTimestamp="1388686826" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1279246063" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
